src/modules/post/models.py
from src.extensions.database import PkModel, db
from datetime import datetime


class Post(PkModel):
    slug =  db.Column(db.String(255), unique=True)
    title = db.Column(db.String(255))
    content = db.Column(db.Text)
    poster_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    likes = db.relationship('PostLike', backref='post', lazy='dynamic')
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)

class PostLike(PkModel):
    __tablename__ = 'post_like'
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

src/modules/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, EqualTo
from wtforms import StringField, SubmitField, EmailField, PasswordField


class ProfileForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    email = EmailField("Email: ", validators=[DataRequired()])
    password = PasswordField("Password: ", validators=[DataRequired(), EqualTo('password_confirm', message='Passwords must match')])
    password_confirm = PasswordField("Confirm password: ", validators=[DataRequired()])
    submit = SubmitField("Submit")

src/modules/post/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField, SubmitField, EmailField, PasswordField, TextAreaField


class PostForm(FlaskForm):
    slug = StringField("Slug: ", validators=[DataRequired()])
    title = StringField("Title: ", validators=[DataRequired()])
    content = TextAreaField("Content: ", validators=[DataRequired()])
    submit = SubmitField("Submit")

src/app.py
import logging

from flask import Flask, render_template
from src.settings import settings
from src.extensions import extensions, extensions_with_db, login_manager
from src.extensions.database import db
from src.modules.auth.models import User


def import_models():
    # Course models
    from src.modules.auth.models import User


def register_extensions(app):
    """Register Flask extensions."""
    for extension in extensions:
        extension.init_app(app=app)

    for extension in extensions_with_db:
        extension.init_app(app=app, db=db)


def register_blueprints(app: Flask):
    """
    Method to register list of blueprints to the app

    param app: Flask application
    """
    # To check if app contains blueprints we need to be inside the app context
    from src.blueprints import blueprints

    if not blueprints and app.get("CHECK_FOR_BLUEPRINTS") is True:
        message = "The list of blueprints is empty. App won't have any blueprints."
        logging.warning(message)
    else:
        for blueprint in blueprints:
            app.register_blueprint(blueprint)


def register_error_handlers(app):
    @app.errorhandler(404)
    def error_code_404(e):
        return render_template('error_pages/404.html'), 404

    @app.errorhandler(500)
    def error_code_500(e):
        return render_template("error_pages/500.html"), 500


def register_shell_context(app):
    pass


def register_commands(app):
    pass


def configure_logger(app):
    pass


def create_app():

    app = Flask(__name__)
    app.config.from_object(settings)

    register_extensions(app)
    register_blueprints(app)
    register_error_handlers(app)
    register_shell_context(app)
    register_commands(app)
    configure_logger(app)
    import_models()

    @login_manager.user_loader
    def load_user(user_id):
        return User.get_by_id(user_id)

    return app

src/blueprints.py
from flask import Blueprint
from src.extensions.api import  api_blueprint
from src.modules.auth.views import auth_blueprint
from src.modules.main.views import main_blueprint
from src.modules.post.views import post_blueprint
from src.modules.searchbar.views import searchbar_blueprint
from src.modules.dashboard.views import dashboard_blueprint

blueprints: list[Blueprint] = [auth_blueprint, main_blueprint, dashboard_blueprint, post_blueprint, searchbar_blueprint, api_blueprint]

src/extensions/__init__.py
# -*- coding: utf-8 -*-
"""Extensions module. Each extension is initialized in the app factory located in app.py."""
from flask_login import LoginManager
from flask_migrate import Migrate

from src.extensions.database import db

login_manager = LoginManager()
migrate = Migrate()

login_manager.login_view = "auth.login"

extensions = [login_manager, db]
extensions_with_db = [migrate]

src/modules/dashboard/views.py
from flask import Blueprint, render_template
from src.modules.auth.models import User, db
from flask_login import login_required, current_user

dashboard_blueprint = Blueprint(
    "dashboard", __name__, template_folder="templates", url_prefix=""
)

@dashboard_blueprint.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    id = current_user.id
    return render_template("dashboard.html", id=id)

src/modules/main/views.py
from flask import Blueprint, render_template

main_blueprint = Blueprint(
    "main", __name__, template_folder="templates"
)


@main_blueprint.route('/')
def main():
    return render_template("index.html")

src/modules/post/views.py
from src.modules.auth.models import User
from src.modules.post.models import Post, db
from src.modules.post.forms import PostForm
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user


post_blueprint = Blueprint(
    "post", __name__, template_folder="templates", url_prefix="/blog"
)


@post_blueprint.route('/')
def blog():
    posts = Post.query.order_by(Post.date_posted)
    return render_template("blog.html", posts=posts)


@post_blueprint.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        poster = current_user.id
        print(poster)
        filter_post = Post.query.filter_by(slug=form.slug.data).first()

        if filter_post is None:
            new_post = Post().create(
                slug=form.slug.data,
                poster_id=poster,
                title=form.title.data,
                content=form.content.data
            )

            db.session.add(new_post)
            db.session.commit()
            flash("Post submitted")
            return redirect(url_for('post.blog'))
        else:
            flash("Post already exists")
    return render_template("add_post.html", form=form)


@post_blueprint.route('/post/<string:slug>')
def show_post(slug):
    post = Post.query.filter_by(slug=slug).first()
    if post:
        return render_template("show_post.html", post=post, slug=slug)
    else:
        return render_template("blog.html")


@post_blueprint.route('/post/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    form = PostForm()
    update_post = Post.query.get_or_404(id)

    id = current_user.id
    if id == update_post.poster.id:
        if request.method == "POST":
            update_post.slug = request.form['slug']
            update_post.title = request.form['title']
            update_post.content = request.form['content']
            try:
                db.session.commit()
                flash("Post updated")
                return redirect(url_for("post.blog"))
            except:
                flash("Error while updating")
    else:
        flash("Access Denied")
        return redirect(url_for("post.blog"))

    return render_template("edit_post.html", form=form, update_post=update_post, id=id)


@post_blueprint.route("/posts/delete/<int:id>")
@login_required
def delete_post(id):
    delete_post = Post.query.get_or_404(id)

    id = current_user.id
    if id == delete_post.poster.id:
        try:
            db.session.delete(delete_post)
            db.session.commit()
            flash("Post deleted")
            return redirect(url_for('post.blog'))
        except:
            flash("Error occurred")
        return render_template("post.html", form=form)
    else:
        flash("Access denied for deleting post")
        return redirect(url_for('post.blog'))


@post_blueprint.route("/<action>/<int:id>")
@login_required
def like_action(action, id):
    post = Post.query.filter_by(id=id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

src/modules/searchbar/views.py
from flask import Blueprint
from src.modules.post.models import Post



searchbar_blueprint = Blueprint(
    "search", __name__, template_folder="templates", url_prefix="/blog"
)
# Pass form page to navbar for search
@searchbar_blueprint.context_processor
def base():
    form = SearchForm()
    posts = Post.query
    return dict(form=form, posts=posts)


@searchbar_blueprint.route("/search", methods=["POST"])
def search():
    form = SearchForm()
    posts = Posts.query

    if form.validate_on_submit():
        post.searched = form.searched.data
        posts = posts.filter(Posts.content.like('%' + post.searched + '%'))\
            .order_by(Posts.title).all()

        return render_template("search.html", form=form, searched=post.searched, posts=posts)

src/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/style.css') }}"  rel="stylesheet">
  </head>
  <body>
    {% include 'navbar.html'%}
    <br/>
    <div class="container">
    {% block main %}
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/navbar.html
<link href="{{ url_for('static', filename='css/navbar.css') }}"  rel="stylesheet">
<nav class="navbar navbar-expand-lg  navbar-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-main" href="{{ url_for('main.main') }}">Myblog</a>
        </li>
      </ul>
        <div class="components">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('post.blog') }}">Posts</a>
                </li>

                {% if current_user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('dashboard.dashboard') }}">Profile</a>
                </li>


                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}">Sign In</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
                </li>

                {% endif %}
            </ul>
        </div>
        <dev class="search-bar">
            <form method="POST" action="#" class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
            <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </dev>
    </div>
  </div>
</nav>