src/modules/post/models.py
from src.extensions.database import PkModel, db
from datetime import datetime


class Post(PkModel):
    slug =  db.Column(db.String(255), unique=True)
    title = db.Column(db.String(255))
    content = db.Column(db.Text)
    poster_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    likes = db.relationship('PostLike', backref='post', lazy='dynamic')
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)

class PostLike(PkModel):
    __tablename__ = 'post_like'
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

src/modules/post/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField, SubmitField, EmailField, PasswordField, TextAreaField


class PostForm(FlaskForm):
    slug = StringField("Slug: ", validators=[DataRequired()])
    title = StringField("Title: ", validators=[DataRequired()])
    content = TextAreaField("Content: ", validators=[DataRequired()])
    submit = SubmitField("Submit")

src/modules/post/views.py
from src.modules.auth.models import User
from src.modules.post.models import Post, db
from src.modules.post.forms import PostForm
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user


post_blueprint = Blueprint(
    "post", __name__, template_folder="templates", url_prefix="/blog"
)


@post_blueprint.route('/')
def blog():
    posts = Post.query.order_by(Post.date_posted)
    return render_template("blog.html", posts=posts)


@post_blueprint.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        poster = current_user.id
        print(poster)
        filter_post = Post.query.filter_by(slug=form.slug.data).first()

        if filter_post is None:
            new_post = Post().create(
                slug=form.slug.data,
                poster_id=poster,
                title=form.title.data,
                content=form.content.data
            )

            db.session.add(new_post)
            db.session.commit()
            flash("Post submitted")
            return redirect(url_for('post.blog'))
        else:
            flash("Post already exists")
    return render_template("add_post.html", form=form)


@post_blueprint.route('/post/<string:slug>')
def show_post(slug):
    post = Post.query.filter_by(slug=slug).first()
    if post:
        return render_template("show_post.html", post=post, slug=slug)
    else:
        return render_template("blog.html")


@post_blueprint.route('/post/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    form = PostForm()
    update_post = Post.query.get_or_404(id)

    id = current_user.id
    if id == update_post.poster.id:
        if request.method == "POST":
            update_post.slug = request.form['slug']
            update_post.title = request.form['title']
            update_post.content = request.form['content']
            try:
                db.session.commit()
                flash("Post updated")
                return redirect(url_for("post.blog"))
            except:
                flash("Error while updating")
    else:
        flash("Access Denied")
        return redirect(url_for("post.blog"))

    return render_template("edit_post.html", form=form, update_post=update_post, id=id)


@post_blueprint.route("/posts/delete/<int:id>")
@login_required
def delete_post(id):
    delete_post = Post.query.get_or_404(id)

    id = current_user.id
    if id == delete_post.poster.id:
        try:
            db.session.delete(delete_post)
            db.session.commit()
            flash("Post deleted")
            return redirect(url_for('post.blog'))
        except:
            flash("Error occurred")
        return render_template("post.html", form=form)
    else:
        flash("Access denied for deleting post")
        return redirect(url_for('post.blog'))


@post_blueprint.route("/<action>/<int:id>")
@login_required
def like_action(action, id):
    post = Post.query.filter_by(id=id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

src/modules/post/templates/add_post.html
{% extends "layout.html" %}

{% block title %}
    Blog
{% endblock %}


{% block main %}

{% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}


<br/><br/>
<center><h1>Create new post</h1></center>
<br/><br/>

<div style="justify-content:center; display: flex;">
    <div class="w-75 shadow-lg p-3 mb-5 rounded">
        <form method="POST">
            {{ form.hidden_tag() }}

            {{ form.slug.label(class="form-label") }}
            {{ form.slug(class="form-control") }}
            <br/>
            {{ form.title.label(class="form-label") }}
            {{ form.title(class="form-control") }}
            <br/>
            {{ form.content.label(class="form-label") }}
            {{ form.content(class="form-control", rows="4") }}
            <br/>
            {{ form.submit(class="btn btn-secondary") }}
        </form>
    </div>
</div>

{% endblock %}

src/modules/post/templates/blog.html
{% extends "layout.html" %}

{% block title %}
    Blog
{% endblock %}


{% block main %}

{% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<div style="text-align: right; position:relative; top:55px; left:120px;">
    <a class="btn btn-info" href="{{ url_for('post.post') }}">Create New Post</a>
</div>

<center><h1>Blog posts</h1></center>
<br/><br/><br/>
<div style="justify-content:center; display: relative;">
    {% for post in posts %}
        <center>
            <div style="background-color: #6f706f;" class="w-75 shadow-lg p-3 mb-5 rounded">
                <div align="left">
                    <center><h2>{{ post.title | capitalize }}</h2></center>
                    By: {{ post.poster.username }}
                    <br/>
                    slug: {{ post.slug }}
                    <br/>
                    content: {{ post.content | safe }}
                    <br/><br/><br/>

                    <a class="btn btn-success" href="{{ url_for('post.show_post', slug=post.slug) }}">Show</a>
                    <a class="btn btn-light" href="{{ url_for('post.update', slug=post.slug, id=post.id) }}">Edit</a>
                    <a class="btn btn-danger" href="{{ url_for('post.delete_post', slug=post.slug, id=post.id) }}">Delete</a>

                    {% if current_user.is_authenticated %}
                        {% if current_user.has_liked_post(post) %}
                            <a style="position: relative; left: 635px;" class="btn btn-secondary" href="{{ url_for('post.like_action', id=post.id, action='unlike') }}">Unlike</a>
                        {% else %}
                            <a style="position: relative; left: 635px;" class="btn btn-primary" href="{{ url_for('post.like_action', id=post.id, action='like') }}">Like</a>
                        {% endif %}
                    {% else %}
                        <a style="position: relative; left: 635px;" class="btn btn-primary" href="{{ url_for('post.like_action', id=post.id, action='like') }}">Like</a>
                    {% endif %}
                </div>
            </div>
        </center>
    {% endfor %}
</div>


{% endblock %}

src/modules/post/templates/edit_post.html
{% extends "layout.html" %}

{% block title %}
    Post Update
{% endblock %}


{% block main %}

{% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<div style="text-align: center;">
    <h1>This is update page</h1>
</div>
<br/><br/>

<div style="justify-content:center; display: flex;">
    <div style="background-color: #50D4FD;" class="w-75 shadow-lg p-3 mb-5 rounded">
        <form action="{{ update_post.id }}" method="POST">
                {{ form.hidden_tag() }}

                {{ form.slug.label(class="form-label") }}
                {{ form.slug(class="form-control", value=update_post.slug) }}
                <br/>
                {{ form.title.label(class="form-label") }}
                {{ form.title(class="form-control", value=update_post.title) }}
                <br/>
                {{ form.content.label(class="form-label") }}
                <textarea name="content" class="form-control">{{ update_post.content }}</textarea>
                <br/>
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

src/modules/post/templates/show_post.html
{% extends "layout.html" %}

{% block title %}
    {{ slug }} post
{% endblock %}


{% block main %}
<br/><br/><br/>
<div style="justify-content:center; display: flex;">
    <div class="w-75 shadow-lg p-3 mb-5 rounded">
        <h2>{{ post.title }}</h2>
        By: {{ post.poster.username }}<br>
        Slug: {{ post.slug }}<br>
        Content: {{ post.content | safe }} <br/>
        Post ID: {{ post.id }}
        <br/><br/>
        <a class="btn btn-secondary" href="{{ url_for('post.blog') }}">Back To Blog</a>
        <br/>
    </div>
</div>
{% endblock %}